---
abstract: "an interface to Sprint's web services"
author:
  - 'Brett T. Warden <bwarden@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Sprint
provides:
  WebService::Sprint:
    file: lib/WebService/Sprint.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
